---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: akhbari-us-staging
  namespace: nginx
spec:
  secretName: akhbari-us-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.akhbari.us"
  dnsNames:
  - "*.akhbari.us"
