---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - ${ingress_range}

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: adverise-all
  namespace: metallb-system
