apiVersion: v1
kind: Secret
metadata:
  name: ${SERVICE_ACCT}-token
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/service-account.name: ${SERVICE_ACCT}
type: kubernetes.io/service-account-token